% Person
SentenceCodes(1,:) = {'Claudia','Carmen','Elena','Teresa', 'Josefa',...
                        'Jose','Antonio', 'Carlos', 'Pedro', 'Manuel', '-'};
WordOrder(1,:) = [8,9,2,1,3,...
                    6,5,10,9,4, 11];
% Verb
SentenceCodes(2,:) = {'tiene','hace','toma','busca','quiere',...
                 'compra','pinta','mira','pierde','vende', '-'};
WordOrder(2,:) = [4,6,2,8,9,...
                    7,5,1,3,10, 11];
% Number
SentenceCodes(3,:) = {'dos', 'tres','doce','siete','seis',...
                'diez', 'cuatro', 'veinte', 'ocho', 'mil', '-'};
WordOrder(3,:) = [1,2,7,5,4,...
                    9,6,3,8,10, 11];
% Noun
SentenceCodes(4, :) = {'libros','barcos','platos','regalos','guantes',...
                 'zapatos','juegos','dados','sillones','anillos', '-'};
WordOrder(4,:) = [10,2,8,5,7,...
                    1,3,4,9,6, 11];
% Color
SentenceCodes(5,:) = {'grandes','viejos','nuevos','pequeños','enormes',...
                'azules','bellos','lindos','baratos','negros', '-'};
WordOrder(5,:) = [6,9,7,5,1,...
                    8,10,3,4,2, 11];


        