% Person
SentenceCodes(1,:) = {'Jean-Luc','Emile','Agnès','Julien', 'Etienne',...
                        'Michel','Eugène', 'Félix', 'Charlotte', 'Sophie', '-'};
WordOrder(1,:) = [7,3,1,8,4,...
                    9,5,6,2,10, 11];
% Verb
SentenceCodes(2,:) = {'ramasse','voudrait','attrape','dessine','demande',...
                 'ramène','reprend','achète','propose','déplace', '-'};
WordOrder(2,:) = [7,10,2,5,3,...
                    8,9,1,6,4, 11];
% Number
SentenceCodes(3,:) = {'trois', 'deux','quinze','huit','douze',...
                'onze', 'neuf', 'six', 'cinq', 'sept', '-'};
WordOrder(3,:) = [2,1,10,6,9,...
                    8,7,4,3,5, 11];
% Noun
SentenceCodes(4, :) = {'classeurs','livres','crayons','piquets','vélos',...
                 'jetons','ballons','anneaux','rubans','pions', '-'};
WordOrder(4,:) = [3,6,4,8,10,...
                    5,2,1,9,7, 11];
% Color
SentenceCodes(5,:) = {'jaunes','rouges','verts','bruns','bleus',...
                'mauves','roses','blancs','gris','noirs', '-'};
WordOrder(5,:) = [5,9,10,3,2,...
                    6,8,1,4,7, 11];


        